const mongoose = require('mongoose');

const PropertySchema = new mongoose.Schema({
    propertyID:               { type: mongoose.Schema.Types.Mixed, unique: true, index: true },
    branchID:                 String,
    clientName:               String,
    branchName:               String,
    department:               String,
    referenceNumber:          String,
    addressName:              String,
    addressNumber:            String,
    addressStreet:            String,
    address2:                 String,
    address3:                 String,
    address4:                 String,
    addressPostcode:          String,
    country:                  String,
    displayAddress:           String,
    propertyFeature1:         String,
    propertyFeature2:         String,
    propertyFeature3:         String,
    propertyFeature4:         String,
    propertyFeature5:         String,
    propertyFeature6:         String,
    propertyFeature7:         String,
    propertyFeature8:         String,
    propertyFeature9:         String,
    propertyFeature10:        String,
    dateLastModified:         String,
    timeLastModified:         String,
    featuredProperty:         String,
    regionID:                 String,
    latitude:                 String,
    longitude:                String,
    flags:                    mongoose.Schema.Types.Mixed,
    mainSummary:              String,
    fullDescription:          String,
    // Residential
    propertyBedrooms:         String,
    propertyBathrooms:        String,
    propertyEnsuites:         String,
    propertyReceptionRooms:   String,
    propertyKitchens:         String,
    propertyAge:              String,
    floorArea:                String,
    floorAreaUnits:           String,
    displayPropertyType:      String,
    propertyType:             String,
    propertyStyle:            String,
    // Sales
    availability:             String,
    price:                    Number,
    forSalePOA:               String,
    priceQualifier:           String,
    propertyTenure:           String,
    saleBy:                   String,
    tenure:                   String,
    developmentOpportunity:   String,
    investmentOpportunity:    String,
    estimatedRentalIncome:    String,
    // Lettings
    rent:                     Number,
    rentFrequency:            String,
    toLetPOA:                 String,
    studentProperty:          String,
    lettingFeePolicyHeadline: String,
    lettingFeePolicyDetails:  String,
    // Commercial
    forSale:                  String,
    toLet:                    String,
    priceTo:                  Number,
    priceFrom:                Number,
    rentTo:                   Number,
    rentFrom:                 Number,
    floorAreaTo:              String,
    floorAreaFrom:            String,
    siteArea:                 String,
    siteAreaUnits:            String,
    strapLine:                String,
    propertyTypes:            mongoose.Schema.Types.Mixed,
    // Agricultural
    landAreaTo:               String,
    landAreaFrom:             String,
    landAreaUnits:            String,
    forSaleLeaseLength:       String,
    // Media (stored as arrays)
    images:                   mongoose.Schema.Types.Mixed,
    floorplans:               mongoose.Schema.Types.Mixed,
    epcGraphs:                mongoose.Schema.Types.Mixed,
    epcFrontPages:            mongoose.Schema.Types.Mixed,
    brochures:                mongoose.Schema.Types.Mixed,
    virtualTours:             mongoose.Schema.Types.Mixed,
    externalLinks:            mongoose.Schema.Types.Mixed,
    // Status
    status:                   { type: Number, default: 1 },
    deleted_at:               Date,
}, { timestamps: true });

PropertySchema.index({ status: 1 });
PropertySchema.index({ displayAddress: 'text', addressStreet: 'text', addressPostcode: 'text', address2: 'text', address3: 'text' });

module.exports = mongoose.model('Property', PropertySchema);
